name = "xiaban-kitchen-api"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "xiaban-kitchen-db"
database_id = "3b63e30f-bd7c-4a0b-bfbf-22f516987d5e"

[env.production]
vars = { ENV = "production" }

[observability]
enabled = true
head_sampling_rate = 1
